global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: null #  Здесь указываем 'null' receiver

receivers:
  # Никаких receivers здесь не нужно
