volumes:
  prometheus_data: 
  grafana_data: {}

networks:
  hohlenkovav-my-netology-hw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

services:
  pushgateway:
    image: prom/pushgateway
    container_name: hohlenkovav-netology-pushgateway
    networks:
      - hohlenkovav-my-netology-hw
    ports:
      - "9091:9091"

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - hohlenkovav-my-netology-hw
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  hohlenkovav-netology-prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus_data
    ports:
      - "9090:9090"
    networks:
      - hohlenkovav-my-netology-hw
    depends_on:
      - pushgateway
      - alertmanager

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - 9100:9100
    networks:
      - hohlenkovav-my-netology-hw
    restart: always
    deploy:
      mode: global

  process_exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    volumes:
      - /proc:/host/proc
      - ./process-exporter.yml:/config/process-exporter.yml
    ports:
      - 9256:9256
    privileged: true
    command:
      - -procfs=/host/proc
      - -config.path=/config/process-exporter.yml
    networks:
      - hohlenkovav-my-netology-hw
      

  grafana:
    image: grafana/grafana
    #user: "472"
    depends_on:
      - hohlenkovav-netology-prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./custom.ini:/etc/grafana/grafana.ini
    env_file:
      - ./grafana/config.monitoring
    networks:
      - hohlenkovav-my-netology-hw
 #     - front-tier
    restart: always


  dnsmasq:
    image: debian:bullseye-slim
    container_name: dnsmasq
    networks:
      - hohlenkovav-my-netology-hw
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y dnsmasq && dnsmasq -C /etc/dnsmasq.conf"]
